resources:
- ../generators

patchesStrategicMerge:
- |-
  apiVersion: builtin
  kind: HelmChartInflationGenerator
  metadata:
    name: myMap
  name: minecraft
  repo: https://itzg.github.io/minecraft-server-charts
  version: 3.1.3
  releaseName: test
